### ISSUE TITLE
why do you use Actor Akka

### ISSUE THREAD

**Issue by fizz12344321** [grantzayne/Cake_Concurrency#1]
Hi, i am reading your project, why do you choose Akka Actor for working as High concurrency, can u tell me the reason, the pros and cons of Actor Akka, why don't you choose another reactive stream like RxJava, Reactive...

**Comment by grantzayne** [comment]
Hi, so been a really long time since I've looked at this. This is a project I did in university for a course in concurrency, so the goal wasn't exactly to make something super efficient and amazing, more to understand the logic behind how concurrency works. As for why we didn't use RxJava or Reactive, I couldn't really tell you as I don't have the knowledge to be able to tell you, I suppose our lecturer thought using Akka Actors would more easily get the point across.
